spring:
  datasource:
    url: jdbc:h2:~/db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  jpa:
    properties:
      hibernate.format_sql: true
      databasePlatform: "org.hibernate.dialect.H2Dialect"
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console
server:
  error:
    include-message: always